/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import portfolio from "../assets/3d/portfolio.glb";

const PalletTown = (props) => {
  const isTownRef = useRef();
  const { nodes, materials } = useGLTF(portfolio);
  return (
    <a.group {...props}>
      <group
        ref={isTownRef}
        position={[6.457, 0.4, 9.797]}
        scale={[0.045, 0.4, 0.03]}
      >
        <mesh
          geometry={nodes.Cube017.geometry}
          material={materials.C_NameBoard}
        />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["Red.001"]}
        />
      </group>
      <group position={[-10.713, 0.4, -2.895]} scale={[0.045, 0.4, 0.03]}>
        <mesh
          geometry={nodes.Cube039.geometry}
          material={materials.C_NameBoard}
        />
        <mesh
          geometry={nodes.Cube039_1.geometry}
          material={materials["Red.001"]}
        />
      </group>
      <group position={[4.869, 0.4, -2.895]} scale={[0.045, 0.4, 0.03]}>
        <mesh
          geometry={nodes.Cube040.geometry}
          material={materials.C_NameBoard}
        />
        <mesh
          geometry={nodes.Cube040_1.geometry}
          material={materials["Red.001"]}
        />
      </group>
      <group position={[-3.633, 0.4, 5.672]} scale={[0.045, 0.4, 0.03]}>
        <mesh
          geometry={nodes.Cube041.geometry}
          material={materials.C_NameBoard}
        />
        <mesh
          geometry={nodes.Cube041_1.geometry}
          material={materials["Red.001"]}
        />
      </group>
      <group position={[0, -1, 0]} scale={20}>
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane008_2.geometry}
          material={materials.M_Brown}
        />
        <mesh
          geometry={nodes.Plane008_3.geometry}
          material={materials.M_Blue}
        />
        <mesh
          geometry={nodes.Plane008_4.geometry}
          material={materials.M_Flower_Yellow}
        />
        <mesh
          geometry={nodes.Plane008_5.geometry}
          material={materials.M_Flower_Red}
        />
        <mesh
          geometry={nodes.Plane008_6.geometry}
          material={materials.M_Flower_Green}
        />
        <mesh
          geometry={nodes.Plane008_7.geometry}
          material={materials.M_Flower_Green_Light}
        />
        <mesh
          geometry={nodes.Plane008_8.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane008_9.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Plane008_10.geometry}
          material={materials["Wall.001"]}
        />
        <mesh geometry={nodes.Plane008_11.geometry} material={materials.Gray} />
        <mesh
          geometry={nodes.Plane008_12.geometry}
          material={materials["Indoor_Window.001"]}
        />
        <mesh
          geometry={nodes.Plane008_13.geometry}
          material={materials.Black_Window}
        />
        <mesh
          geometry={nodes.Plane008_14.geometry}
          material={materials.M_House_Wall}
        />
        <mesh
          geometry={nodes.Plane008_15.geometry}
          material={materials.M_House1_EdgeWindow}
        />
        <mesh
          geometry={nodes.Plane008_16.geometry}
          material={materials.M_Indoor_window}
        />
        <mesh
          geometry={nodes.Plane008_17.geometry}
          material={materials.M_House1_Root}
        />
        <mesh
          geometry={nodes.Plane008_18.geometry}
          material={materials.M_House1_EdgeWindow_Dark}
        />
        <mesh
          geometry={nodes.Plane008_19.geometry}
          material={materials.M_House1_Door}
        />
        <mesh
          geometry={nodes.Plane008_20.geometry}
          material={materials.M_House1_Brick}
        />
        <mesh
          geometry={nodes.Plane008_21.geometry}
          material={materials.Fence_Color}
        />
        <mesh
          geometry={nodes.Plane008_22.geometry}
          material={materials["Wall.002"]}
        />
        <mesh
          geometry={nodes.Plane008_23.geometry}
          material={materials["Gray.001"]}
        />
      </group>
    </a.group>
  );
};

export default PalletTown;
